### ISSUE TITLE
Is there any theoretical reference for this code? If yes can you please share

### ISSUE THREAD

**Issue by shivamsehgal77** [shimodatakaki/MultirateChatterAnalysis#1]

**Comment by shimodatakaki** [comment]
Please see the following paper on the IEEE website.

https://ieeexplore.ieee.org/abstract/document/8217172

T. Shimoda and H. Fujimoto, "Adaptive spindle-speed selection for chatter avoidance to achieve high-precision NC machining based on semi-discretization method," IECON 2017 - 43rd Annual Conference of the IEEE Industrial Electronics Society, Beijing, China, 2017, pp. 6709-6714, doi: 10.1109/IECON.2017.8217172.

**Comment by shivamsehgal77** [comment]
Thanks!!
